#!/bin/bash
#######################  sfs-bootstrap ####################################
#
# Copyright 2018, 2022  J. E. Garrott Sr, Puyallup, WA, USA
# Copyright 2018, 2022  "nobodino", Bordeaux, FRANCE
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#--------------------------------------------------------------------------
#
#	Above july 2018, revisions made through github project: 
#   
#   https://github.com/nobodino/slackware-from-scratch 
#
#*******************************************************************
# set -xv
#*******************************************************************

test_root () {
#*************************************
# test if user is ROOT, if not exit
#*************************************
[ "$UID" != "0" ] && error "You must be ROOT to execute that script."
}

distribution_selector () {
#**********************************
# distribution selector
#**********************************
PS3="Your choice:"
select distribution in slackware quit
do
	if [[ "$distribution" != "quit" ]]
	then
		break
	fi
	echo
	echo -e "$RED" "You have decided to quit. Goodbye." "$NORMAL"  && exit 1
done
echo -e "$BLUE" "You chose $distribution."  "$NORMAL" 
echo

}

arch_selector () {
#**********************************
# architecture selector
#**********************************
PS3="Your choice:"
select build_arch in x86 x86_64 quit
do
	if [[ "$build_arch" = "x86" ]]
	then
		if [[ "$distribution" = "slackware" ]]
		then
			tools_dir1='tools_x86'
			echo
			echo -e "$BLUE" "You chose $tools_dir1" "$NORMAL"
			echo
			break
		fi
		break
	elif [[ "$build_arch" = "x86_64" ]]
	then
		if [[ "$distribution" = "slackware" ]]
		then
			tools_dir1='tools_x86_64'
			echo
			echo -e "$BLUE" "You chose $tools_dir1" "$NORMAL"
			echo
			break
		fi
		break
	elif [[ "$build_arch" = "quit" ]]
	then
		echo
		echo -e "$RED" "You have decided to quit. Goodbye." "$NORMAL" && exit 1
	fi
done
echo
echo -e "$BLUE"  "You chose $build_arch." "$NORMAL"
echo

}

dev_selector () {
#**********************************
# -current or -dev selector
#**********************************
PS3="Your choice:"
select dev_select in current development quit
do
	if [[ "$dev_select" = "current" ]]; then
		if [[ "$build_arch" = "x86" ]]; then
			tools_dir='tools'
			echo
			echo -e "$BLUE" "You chose $tools_dir" "$NORMAL"
			echo
			break
		elif [[ "$build_arch" = "x86_64" ]]; then
			tools_dir='tools_64'
			echo
			echo -e "$BLUE" "You chose $tools_dir" "$NORMAL"
			echo
			break
		fi
		break
	elif [[ "$dev_select" = "development" ]]; then
		if [[ "$build_arch" = "x86" ]]; then
			tools_dir='tools_dev'
			echo
			echo -e "$BLUE" "You chose $tools_dir" "$NORMAL"
			echo
			break
		elif [[ "$build_arch" = "x86_64" ]]; then
			tools_dir='tools_64_dev'
			echo
			echo -e "$BLUE" "You chose $tools_dir" "$NORMAL"
			echo
			break
		fi
		break
	elif [[ "$dev_select" = "quit" ]]
	then
		echo
		echo -e "$RED" "You have decided to quit. Goodbye." "$NORMAL" && exit 1
	fi
done
echo
echo -e "$BLUE"  "You chose $dev_select." "$NORMAL"
echo
#**********************************************
# defines RDIR according to x86 or x86_64:
#**********************************************
	if [[ "$distribution" = "slackware" ]]; then
		if [[ "$build_arch" = "x86" ]]; then
			export RDIR="$RDIR1"
		elif [[ "$build_arch" = "x86_64" ]]; then
			export RDIR="$RDIR3"
		fi
	fi
	echo "****** $RDIR ******"

}

clean_sfs () {
#**********************************
# Clear $SFS
#**********************************
cd "$SFS" || exit 1
if (mount -l -t proc |grep sfs >/dev/null); then
	umount -v "$SFS"/dev/pts
	umount -v "$SFS"/dev
	umount -v "$SFS"/proc
	umount -v "$SFS"/sys
	umount -v "$SFS"/run
fi

[ -d "$SFS"/proc ] && rm -rf bin boot dev etc jre home lib media mnt \
	lib64 opt proc root run sbin slackware64 slackware srv sys tmp tools usr var font*

}

rsync_src () {
#*************************************
# Upgrade the sources by rsyncing 
#*************************************
echo "Do you want to upgrade the sources of SFS? No, Yes or Quit."
PS3="Your choice:"
select upgrade_sources in Yes No Quit
do
	if [[ "$upgrade_sources" = "Quit" ]]
	then
		echo  -e "$RED" "You have decided to quit. Goodbye." "$NORMAL" && exit 1
	elif [[ "$upgrade_sources" = "Yes" ]]
	then
		echo "You chose to upgrade the sources of SFS."
		echo
		echo "rsync the slackware source tree from a slackware mirror"
		mkdir "$SFS"/scripts/others > /dev/null 2>&1
		cp -r --preserve=timestamps "$SRCDIR"/others/* "$SFS"/scripts/others > /dev/null 2>&1
		mkdir "$SFS"/scripts/extra > /dev/null 2>&1
		cp -r --preserve=timestamps "$SRCDIR"/extra/* "$SFS"/scripts/extra > /dev/null 2>&1
		rsync -arvz --stats --progress -I --delete-after "$RSYNCDIR"/source/ "$SRCDIR"
		mkdir "$SRCDIR"/others > /dev/null 2>&1
		cp -r --preserve=timestamps "$SFS"/scripts/others/* "$SRCDIR"/others > /dev/null 2>&1
		mkdir "$SRCDIR"/extra > /dev/null 2>&1
		cp -r --preserve=timestamps  "$SFS"/scripts/extra/* "$SRCDIR"/extra > /dev/null 2>&1
		rsync -arvz --stats --progress -I --delete-after "$RSYNCDIR"/extra/source/ "$SRCDIR"/extra > /dev/null 2>&1
		cp -r "$SFS"/scripts/build/* "$SRCDIR" > /dev/null 2>&1
		cd "$SFS"/scripts || exit 1
		rm end* > /dev/null 2>&1
		rm ./*.t?z > /dev/null 2>&1
		rm -rf "$SFS"/scripts/others > /dev/null 2>&1 
		rm -rf "$SFS"/scripts/extra > /dev/null 2>&1
		break
	elif [[ "$upgrade_sources" = "No" ]]
	then
		echo  -e "$YELLOW" "You chose to keep the sources of SFS as they are." "$NORMAL" 
		break
	fi
done

}

upgrade_src () {
#*************************************
# Upgrade the sources from local mirror
#*************************************
echo "Do you want to upgrade the sources of SFS? No, Yes or Quit."
PS3="Your choice:"
select upgrade_sources in Yes No Quit
do
	if [[ "$upgrade_sources" = "Quit" ]]
	then
		echo
		echo -e "$RED" "You have decided to quit. Goodbye." "$NORMAL" && exit 1
	elif [[ "$upgrade_sources" = "Yes" ]]
	then
		echo
		echo "You chose to upgrade the sources of SFS."
		echo
		echo "rsync the slackware source tree from a slackware local mirror"
		rsync -arvz --stats --progress -I --delete-after "$RDIR"/source "$SFS"
		mkdir -pv "$SRCDIR"/others  > /dev/null 2>&1
		mkdir -pv "$SRCDIR"/extra > /dev/null 2>&1
		cp -r --preserve=timestamps "$DNDIR1"/* "$SRCDIR"/others
		cp -r --preserve=timestamps "$RDIR"/extra/source/* "$SRCDIR"/extra
		case $(uname -m) in
			x86_64 )
				ls "$RDIR"/slackware64/*.t?z > "$SFS"/scripts/list-slackware > /dev/null 2>&1 ;;
			* )
				ls "$RDIR"/slackware/*.t?z > "$SFS"/scripts/list-slackware > /dev/null 2>&1 ;;
		esac
		cp -r "$SFS"/scripts/build/* "$SRCDIR" > /dev/null 2>&1
		rm end* > /dev/null 2>&1
		rm ./*.t?z > /dev/null 2>&1
		rm -rf "$SFS"/scripts/others > /dev/null 2>&1 
		rm -rf "$SFS"/scripts/extra > /dev/null 2>&1
		break
	elif [[ "$upgrade_sources" = "No" ]]
	then
		echo
		echo "You chose to keep the sources of SFS as they are." 
		break
	fi
done

}

rsync_dev_current () {
#*************************************
# download directly from github repository
#*************************************

if [[ "$dev_select" = "current" ]]; then
		echo "You chose the -current branch of slackware to build SFS."
		echo
		rm -rf "$SFS"/source/current && mkdir "$SFS"/source/current
		svn checkout "$DLDIR13"/current "$SFS"/source/current > /dev/null 2>&1
		rm -rf "$SFS"/source/current/.svn
		cp -r --preserve=timestamps "$SFS"/source/current/* "$SFS"/source
		rm -rf "$SFS"/source/current
	elif [[ "$dev_select" = "development" ]]; then
		echo "You chose the -development branch of slackware to build SFS."
		echo
		rm -rf "$SFS"/source/development && mkdir "$SFS"/source/development
		svn checkout "$DLDIR13"/development "$SFS"/source/development > /dev/null 2>&1
		rm -rf "$SFS"/source/development/.svn
		if find "$SFS"/source/development/l/glibc -mindepth 1 | read -r ; then
			rm -rf "$SFS"/source/l/glibc
		fi
		if find "$SFS"/source/development/d/binutils -mindepth 1 | read -r ; then
			rm -rf "$SFS"/source/d/binutils
		fi
		if find "$SFS"/source/development/d/gcc -mindepth 1 | read -r ; then
			rm -rf "$SFS"/source/d/gcc
		fi
		if find "$SFS"/source/development/d/make -mindepth 1 | read -r ; then
			rm -rf "$SFS"/source/d/make
		fi
		if find "$SFS"/source/development/d/automake -mindepth 1 | read -r ; then
			rm -rf "$SFS"/source/d/automake
		fi
		cp -r --preserve=timestamps "$SFS"/source/development/* "$SFS"/source
fi

}

upgrade_dvd () {
#*************************************
# Upgrade the sources from local dvd (blu-ray disc)
#*************************************
echo "Do you want to upgrade the sources of SFS? No, Yes or Quit."
PS3="Your choice: "
select upgrade_sources in Yes No Quit
do
	if [[ "$upgrade_sources" = "Quit" ]] 
	then
		echo
		echo -e "$RED" "You have decided to quit. Goodbye." "$NORMAL" && exit 1
	elif [[ "$upgrade_sources" = "Yes" ]]; then
		echo
		echo "You chose to upgrade the sources of SFS from DVD."
		# Check that dvd has been mounted
		[ ! -d "$RDIR5" ] && mkdir "$RDIR5"
		if ! (mount -l |grep "$RDIR5" >/dev/null); then
			mount /dev/sr0 "$RDIR5"
		fi
		echo "Removing old slackware source."
		[ -d "$SRCDIR" ] && rm -rf "$SRCDIR"
		echo "Installing new sources."
		cp -r --preserve=timestamps "$RDIR5"/source "$SRCDIR"
		mkdir -pv "$SRCDIR"/others  > /dev/null 2>&1
		mkdir -pv "$SRCDIR"/extra > /dev/null 2>&1
		cp -r --preserve=timestamps "$DNDIR1"/* "$SRCDIR"/others
		cp -r --preserve=timestamps "$RDIR5"/extra/source/* "$SRCDIR"/extra
		cd "$SFS"/scripts || exit 1
		rm end* > /dev/null 2>&1
		rm ./*.t?z > /dev/null 2>&1
		rm -rf "$SFS"/scripts/extra && rm -rf "$SFS"/scripts/others
		break
	elif [[ "$upgrade_sources" = "No" ]]
	then
		echo
		echo "You chose to keep the sources of SFS as they are."
		break
	fi
done

}

populate_others () {
#*************************************
# download directly from source to others
#*************************************

if [[ "$build_arch" = "x86" ]]
	then
		mkdir "$SRCDIR"/others > /dev/null 2>&1
		cd "$SRCDIR"/others || exit 1
		if [ ! -f cxxlibs-6.0.18-i486-1.txz ]; then
			wget -c -v "$DLDIR2"/slackware/a/cxxlibs-6.0.18-i486-1.txz
		fi
		if [ ! -f gmp-5.1.3-i486-1.txz ]; then
			wget -c -v "$DLDIR2"/slackware/l/gmp-5.1.3-i486-1.txz
		fi
		if [ ! -f db44-4.4.20-i486-3.txz ]; then
			wget -c -v "$DLDIR2"/slackware/l/db44-4.4.20-i486-3.txz
		fi
		if [ ! -f libelf-0.8.13-i486-2.txz ]; then
			wget -c -v "$DLDIR2"/slackware/l/libelf-0.8.13-i486-2.txz
		fi
		if [ ! -f ncurses-5.9-i486-4.txz ]; then
			wget -c -v "$DLDIR3"/slackware/l/ncurses-5.9-i486-4.txz
		fi
		if [ ! -f readline-6.3-i586-2.txz ]; then
			wget -c -v "$DLDIR3"/slackware/l/readline-6.3-i586-2.txz
		fi
		if [ ! -f libpng-1.4.12-i486-1.txz ]; then
			wget -c -v "$DLDIR2"/slackware/l/libpng-1.4.12-i486-1.txz
		fi
		if [ ! -f ksh93-2012_08_01-i586-2.txz ]; then
			wget -c -v "$DLDIR3"/slackware/ap/ksh93-2012_08_01-i586-2.txz
		fi
		if [ ! -f libcaca-0.99.beta18-i486-2.txz ]; then
			wget -c -v "$DLDIR3"/slackware/l/libcaca-0.99.beta18-i486-2.txz
		fi
		if [ ! -f gcc-gnat-10.3.0-i586-2.txz ]; then
			wget -c -v "$DLDIR14"/gcc-gnat-10.3.0-i586-2.txz
		fi
		cd "$SRCDIR"/d/rust || exit 1
		# shellcheck disable=SC1091 
		sed -i -e '1,22d' rust.url && sed -i -e '9,14d' rust.url && source rust.url
		cd "$SRCDIR"/others || exit 1
		if [ ! -f readline-7.0.005-i586-1.txz ]; then
			wget -c -v "$DLDIR12"/readline-7.0.005-i586-1.txz
		fi
		if [ ! -f libffi-3.2.1-i586-2.txz ]; then
			wget -c -v "$DLDIR12"/libffi-3.2.1-i586-2.txz
		fi
	elif [[ "$build_arch" = "x86_64" ]]
	then
		mkdir "$SRCDIR"/others > /dev/null 2>&1
		cd "$SRCDIR"/others || exit 1
		if [ ! -f cxxlibs-6.0.18-x86_64-1.txz ]; then
			wget -c -v "$DLDIR4"/slackware64/a/cxxlibs-6.0.18-x86_64-1.txz
		fi
		if [ ! -f gmp-5.1.3-x86_64-1.txz ]; then
			wget -c -v "$DLDIR4"/slackware64/l/gmp-5.1.3-x86_64-1.txz
		fi
		if [ ! -f db44-4.4.20-x86_64-3.txz ]; then
			wget -c -v "$DLDIR4"/slackware64/l/db44-4.4.20-x86_64-3.txz
		fi
		if [ ! -f libelf-0.8.13-x86_64-2.txz ]; then
			wget -c -v "$DLDIR4"/slackware64/l/libelf-0.8.13-x86_64-2.txz
		fi
		if [ ! -f ncurses-5.9-x86_64-4.txz ]; then
			wget -c -v "$DLDIR5"/slackware64/l/ncurses-5.9-x86_64-4.txz
		fi
		if [ ! -f readline-6.3-x86_64-2.txz ]; then
			wget -c -v "$DLDIR5"/slackware64/l/readline-6.3-x86_64-2.txz
		fi
		if [ ! -f libpng-1.4.12-x86_64-1.txz ]; then
			wget -c -v "$DLDIR4"/slackware64/l/libpng-1.4.12-x86_64-1.txz
		fi
		if [ ! -f ksh93-2012_08_01-x86_64-2.txz ]; then
			wget -c -v "$DLDIR5"/slackware64/ap/ksh93-2012_08_01-x86_64-2.txz
		fi
		if [ ! -f libcaca-0.99.beta18-x86_64-2.txz ]; then
			wget -c -v "$DLDIR5"/slackware64/l/libcaca-0.99.beta18-x86_64-2.txz
		fi
		cd "$SRCDIR"/others || exit 1
		if [ ! -f "$GNAT_x86_64" ]; then
			wget -c -v "$DLDIR6"/"$GNAT_x86_64" && chmod 644 ./*.tar.gz
		fi
		cd "$SRCDIR"/d/rust || exit 1
		# shellcheck disable=SC1091  
		sed -i -e '1,22d' rust.url && sed -i -e '4,9d' rust.url && source rust.url
		cd "$SRCDIR"/others || exit 1
		if [ ! -f readline-7.0.005-x86_64-1.txz ]; then
			wget -c -v "$DLDIR12"/readline-7.0.005-x86_64-1.txz
		fi
		if [ ! -f libffi-3.2.1-x86_64-2.txz ]; then
			wget -c -v "$DLDIR12"/libffi-3.2.1-x86_64-2.txz
		fi
fi

}

etc_group () {
#***************************************************
mkdir -pv "$SFS"/etc
cat > "$SFS"/etc/group << "EOF"
root:x:0:root
EOF
chmod 644 "$SFS"/etc/group
}

etc_passwd () {
#***************************************************
cat > "$SFS"/etc/passwd << "EOF"
root:x:0:0::/root:/bin/bash
EOF
chmod 644 "$SFS"/etc/passwd
}

root_bashrc () {
#***************************************************
mkdir -pv "$SFS"/root
cat >  "$SFS"/root/.bashrc << "EOF"
#!/bin/sh
LC_ALL=C.UTF-8
export LC_ALL
EOF
}

sfsprep () {
#***********************************************************
# package management: copy tools from slackware source:
#***********************************************************
mkdir -pv "$SFS"/sbin
cp "$SFS"/source/a/pkgtools/scripts/makepkg "$SFS"/sbin/makepkg
cp "$SFS"/source/a/pkgtools/scripts/installpkg "$SFS"/sbin/installpkg
chmod 755 "$SFS"/sbin/makepkg "$SFS"/sbin/installpkg
}

#************************************************************************
#************************************************************************
# MAIN CORE SCRIPT
#************************************************************************
#************************************************************************

#**************************************
# before everything we test if we are root
#**************************************
test_root
. export_variables
. export_variables_perso
distribution_selector
arch_selector
dev_selector

#**************************************
# preparation of $SFS side
#**************************************
mkdir -pv $SRCDIR

cd "$SFS"/scripts || exit 1

#*************************************
# Erase old installation, if any.
#*************************************
echo
echo "Removing old installation."
echo
clean_sfs

#*************************************
# Upgrade the sources from local, rsync or DVD
#*************************************
echo
echo "Do you want to upgrade the sources of SFS? rsync, local, DVD or Quit."
echo
echo "rsync means: it will rsync directly from a slackware mirror defined by"
echo 
echo -e "$BLUE" "$RSYNCDIR" "$NORMAL"
echo
echo "local means: it will rsync from a local slackware mirror you have already rsynced and defined by"
echo
echo -e "$BLUE" "$RDIR1" "$NORMAL"
echo
echo "DVD means: it will rsync from a local slackware DVD (double layer) or BluRay you have already burnt and defined by"
echo
echo -e "$BLUE" "$RDIR5" "$NORMAL"
echo 
PS3="Your choice:"
echo
select upgrade_type in rsync local DVD Quit
do
	if [[ "$upgrade_type" = "Quit" ]]
	then
		echo
		echo  -e "$RED" "You have decided to quit. Goodbye." "$NORMAL" && exit 1
	elif [[ "$upgrade_type" = "rsync" ]]
	then
		echo
		echo -e "$RED" "You chose to rsync slackawre source directly from a slackware mirror." "$NORMAL"
		echo
		cd "$SFS"/scripts || exit 1
		rsync_src
		rsync_dev_current
		populate_others
		break
	elif [[ "$upgrade_type" = "local" ]]
	then
		echo
		echo  -e "$RED" "You chose to rsync slackawre source from a local mirror." "$NORMAL"
		echo 
		upgrade_src
		rsync_dev_current
		populate_others
		break
	elif [[ "$upgrade_type" = "DVD" ]]
	then
		echo
		echo  -e "$RED" "You chose to rsync slackawre source from a local DVD or BluRay." "$NORMAL"
		echo 
		mount -t auto /dev/sr0 /mnt/dvd && sleep 5 && echo -e "$RED" "DVD mounted on /mnt/DVD" "$NORMAL"
		upgrade_dvd
		rsync_dev_current
		populate_others
		umount /mnt/dvd && sleep 3 && eject && echo -e "$RED" "DVD unmounted from /mnt/DVD and ejected." "$NORMAL"
 		break
	fi
done

#*************************************
# create mini /etc/group and /etc/passwd
# to avoid noise while building pkgtools
# "chown: invalid user: 'root:root'"
#*************************************
etc_group
etc_passwd
root_bashrc
#***********************************************************
# package management: copy tools from slackware source
# before chrooting and building slackware
#***********************************************************
sfsprep

cd "$SFS"/scripts || exit 1
. lists_generator
. prep-sfs-tools
#*************************************
# finally chroot in $SFS environment
#*************************************
. chroot_sfs
exit 0
