#!/bin/sh
cd /mnt/ext4/sda4/home/ftp/pub/Linux/Slackware/slackware64-current/slackware64/ && ls */*.*t?z > /home/list-slackware
cd /mnt/sfs/slackware64/ && rm */*_alsa.t?z 2>&1 | tee > /dev/null && ls */*.t?z > /home/list-sfs
cd /home && diff -au list-slackware list-sfs > list.diff
