#!/bin/bash

build_gcc-post () {
#*******************
# export PATH=$PATH_HOLD
# rm -rf /opt/gnat

if [ -f gcc.SlackBuild.old ]; then
	mv -v gcc.SlackBuild{.old,}
fi

cd /scripts || exit 1
}

build_gcc-post
