#!/bin/bash

# Copyright 2006, 2007, 2008, 2009, 2015, 2018  Patrick J. Volkerding, Sebeka, MN, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PKGNAM=netpbm
VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
BUILD=${BUILD:-3}

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) export ARCH=i586 ;;
    arm*) export ARCH=arm ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
       *) export ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
  exit 0
fi

NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX=""
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

TMP=${TMP:-/tmp}
PKG=$TMP/package-${PKGNAM}
rm -rf $PKG
mkdir -p $TMP # Do not create $PKG or 'make package' fails

cd $TMP
rm -rf ${PKGNAM}-${VERSION}
tar xvf $CWD/${PKGNAM}-$VERSION.tar.?z || exit 1
cd ${PKGNAM}-$VERSION

zcat $CWD/netpbm-security-scripts.patch.gz | patch -p1 --verbose || exit 1
#zcat $CWD/netpbm-security-code.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-ppmfadeusage.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-noppmtompeg.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-CVE-2017-2587.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-python3.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-time.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-gcc4.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-bmptopnm.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-CAN-2005-2471.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-xwdfix.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-multilib.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-glibc.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-docfix.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-cmuwtopbm.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-pamtojpeg2k.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-manfix.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-manual-pages.patch.gz | patch -p1 --verbose || exit 1
zcat $CWD/netpbm-libdir-so.patch.gz | patch -p1 --verbose || exit 1

# Send blank lines to "configure" to just take defaults:
./configure << EOF



















EOF

# Make sure ownerships and permissions are sane:
chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \+

# Build and install:
make $NUMJOBS || make || exit 1
make package pkgdir=$PKG || exit 1

# Strip binaries:
find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

# Put things in proper directories:
( cd $PKG
  rm README
  mkdir -p usr
  mv * usr 2> /dev/null
  cd usr
  mkdir -p doc/netpbm-$VERSION
  mv VERSION bin/doc.url doc/netpbm-$VERSION
  if [ -r lib/libnetpbm.so.11 ]; then
    ( cd lib ; rm -f libnetpbm.so ; ln -sf libnetpbm.so.11 libnetpbm.so )
  else
    echo "ERROR:  libnetpbm.so.11 not found."
    echo "Please edit the correct library major version into the build script"
    exit 1
  fi
  mv lib lib${LIBDIRSUFFIX} 2> /dev/null
  # Remove junk directories:
  rm -rf link misc
  # Remove manweb related files:
  rm -rf bin/manweb man/web
  # Any other files in /usr are junk:
  rm --verbose * 2> /dev/null
)

# Don't package the static library:
rm -f $PKG/usr/lib${LIBDIRSUFFIX}/libnetpbm.a

# Create and install man pages for existing utilities:
( cd userguide
  for i in *.html ; do
    ../buildtools/makeman ${i}
  done
  for manpage in *.1 ; do
    if [ ! -r $PKG/usr/bin/$(basename $manpage .1) ]; then
      rm $manpage
    fi
  done
  for i in 1 3 5 ; do
    mkdir -p man/man${i}
    mv *.${i} man/man${i}
  done
  mv man $PKG/usr
)

# Compress and link manpages:
if [ -d $PKG/usr/man ]; then
  ( cd $PKG/usr/man
    for manpagedir in $(find . -type d -name "man*") ; do
      ( cd $manpagedir
        for eachpage in $( find . -type l -maxdepth 1) ; do
          ln -s $( readlink $eachpage ).gz $eachpage.gz
          rm $eachpage
        done
        gzip -9 *.*
      )
    done
  )
fi

# Add a documentation directory:
( cd doc
  cp -a \
  CONTRIBUTORS COPYRIGHT.PATENT GPL_LICENSE.txt HISTORY INSTALL \
  Netpbm.programming USERDOC copyright_summary lgpl_v21.txt \
  patent_summary \
  $PKG/usr/doc/${PKGNAM}-$VERSION
  if [ -r HISTORY ]; then
    DOCSDIR=$(echo $PKG/usr/doc/${PKGNAM}-$VERSION)
    cat HISTORY | head -n 1000 > $DOCSDIR/HISTORY
    touch -r HISTORY $DOCSDIR/HISTORY
  fi
)

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $TMP/${PKGNAM}-$VERSION-$ARCH-$BUILD.txz

