#!/bin/bash
########################## tools_binutils_sp2 ####################
#
# Copyright 2021 "nobodino", Bordeaux, FRANCE
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Note: Much of this script is copied from the LFS manual.
#       Copyright © 1999-2021 Gerard Beekmans and may be
#       copied under the MIT License.
#
###################################################################
tools_binutils_sp2 () {
#*****************************
	export BINUVER=${VERSION:-$(echo binutils-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}

	tar xvf binutils-"$BINUVER".tar.?z || exit 1
	cd binutils-"$BINUVER" || exit 1 
	mkdir -v build
	cd build || exit 1 

	CC="$SFS_TGT"-gcc                \
	AR="$SFS_TGT"-ar                 \
	RANLIB="$SFS_TGT"-ranlib         \
	../configure                   \
		--prefix=/tools            \
		--disable-nls              \
		--disable-werror           \
		--with-lib-path=/tools/lib \
		--with-sysroot || exit 1

	make || exit 1
	make install || exit 1

	make -C ld clean || exit 1
	make -C ld LIB_PATH=/usr/lib:/lib || exit 1
	cp -v ld/ld-new /tools/bin || exit 1

	cd ../..
	rm -rf binutils-"$BINUVER"
	echo binutils-"$BINUVER" >> "$SFS"/tools/etc/tools_version
}

tools_binutils_sp2
