#!/bin/bash

# Copyright 2008, 2009, 2010, 2013, 2015, 2018  Patrick J. Volkerding, Sebeka, MN, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PKGNAM=ppp
VERSION=2.4.7
RADVER=1.1.6
PPPVER=1.98
BUILD=${BUILD:-4}

NUMJOBS=${NUMJOBS:-" -j7 "}

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) export ARCH=i586 ;;
    arm*) export ARCH=arm ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
       *) export ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
  exit 0
fi

if [ "$ARCH" = "x86_64" ]; then
  LIBDIRSUFFIX="64"
else
  LIBDIRSUFFIX=""
fi

TMP=${TMP:-/tmp}
PKG=$TMP/package-ppp

rm -rf $PKG
mkdir -p $TMP $PKG

echo "+============+"
echo "| ppp-$VERSION |"
echo "+============+"
cd $TMP
rm -rf ppp-$VERSION
tar xvf $CWD/ppp-$VERSION.tar.xz || exit 1
cd ppp-$VERSION || exit 1
chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;

zcat $CWD/ppp.slack.diff.gz | patch -p1 --verbose --backup --suffix=.orig || exit 1
sed -i -e "s#lib/pppd#lib${LIBDIRSUFFIX}/pppd#g" $(grep -lr 'lib/pppd' *)

# This conflicts with the header in 3.5+ kernels:
rm -f include/linux/if_pppol2tp.h

zcat $CWD/ppp.CVE-2015-3310.diff.gz | patch -p1 --verbose || exit 1

zcat $CWD/0028-pppoe-include-netinet-in.h-before-linux-in.h.patch.gz | patch -p1 --verbose || exit 1

# patch to build with glibc-2.28
zcat $CWD/ppp-2.4.7-glibc-2.28.patch.gz | patch -Esp1 --verbose || exit 1

./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} || exit 1

make $NUMJOBS || make || exit 1
make install DESTDIR=$PKG/usr || exit 1

# Install PPP config files:
mkdir -p $PKG/etc/ppp
cp -a etc.ppp/* $PKG/etc/ppp
chmod 600 $PKG/etc/ppp/*secrets
( cd $PKG/etc/ppp
  mv chap-secrets chap-secrets.new
  mv options options.new
  mv pap-secrets pap-secrets.new
)
zcat $CWD/options.new.gz > $PKG/etc/ppp/options.new

# Fix what seems like an insecure default setting.
# Feel free to "chmod 4750 pppoatm.so rp-pppoe.so" at your own risk.
# Since they are only runnable by group root, the risk really isn't much...
chmod 755 $PKG/usr/lib${LIBDIRSUFFIX}/pppd/*/*.so

# The Makefile doesn't error out if building rp-pppoe.so fails, so check for it:
if [ ! -r $PKG/usr/lib${LIBDIRSUFFIX}/pppd/${VERSION}/rp-pppoe.so ]; then
  echo "FATAL: /usr/lib${LIBDIRSUFFIX}/pppd/${VERSION}/rp-pppoe.so failed to build."
  exit 1
fi

mkdir -p $PKG/usr/doc/ppp-$VERSION
cp -a \
  FAQ PLUGINS README* SETUP scripts \
  $PKG/usr/doc/ppp-$VERSION

echo "+====================+"
echo "| freeradius-client-$RADVER |"
echo "+====================+"
cd $TMP
rm -rf freeradius-client-$RADVER
tar xf $CWD/freeradius-client-$RADVER.tar.xz || exit 1
cd freeradius-client-$RADVER || exit 1
chown -R root:root .
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --build=$ARCH-slackware-linux || exit 1
make $NUMJOBS || make || exit 1
make install DESTDIR=$PKG || exit 1
zcat $CWD/radius.msdict.gz > $PKG/etc/radiusclient/dictionary.microsoft
zcat $CWD/realms.gz > $PKG/etc/radiusclient/realms
( cd $PKG/etc/radiusclient
  chmod 600 realms servers
  mv issue issue.new
  mv radiusclient.conf radiusclient.conf.new
  mv realms realms.new
  mv servers servers.new
)
mkdir -p $PKG/usr/doc/freeradius-client-$RADVER
cp -a \
  BUGS CHANGES COPYRIGHT README README.radexample doc/instop.html \
  $PKG/usr/doc/freeradius-client-$RADVER
chmod 644 $PKG/usr/doc/freeradius-client-$RADVER/*

echo "+===============+"
echo "| pppsetup-$PPPVER |"
echo "+===============+"
cd $TMP
rm -rf pppsetup-$PPPVER
tar xvf $CWD/pppsetup-$PPPVER.tar.xz || exit 1
cd pppsetup-$PPPVER || exit 1
chown -R root:root .
zcat $CWD/pppsetup-1.98.slack.diff.gz | patch -p1 --backup || exit
zcat $CWD/pppsetup-1.98.pppoff.diff.gz | patch -p0 --backup || exit
zcat $CWD/pppsetup-1.98.moredevs.diff.gz | patch -p1 --backup || exit
zcat $CWD/pppsetup-1.98.backupfiles.diff.gz | patch -p1 --backup || exit
chmod 755 ppp-off pppsetup
cp -a ppp-off pppsetup $PKG/usr/sbin
mkdir -p $PKG/usr/doc/pppsetup
cp -a \
  README.pppsetup ppp-compile.txt pppsetup-$PPPVER.README pppsetup-$PPPVER.lsm \
  $PKG/usr/doc/pppsetup

# Don't ship .la files:
rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . -name "*.a" | xargs file | grep "ar archive" | cut -f 1 -d : | xargs strip -g 2> /dev/null
)

chmod 755 $PKG/usr/sbin/*

gzip -9 $PKG/usr/man/man?/*.?
chmod 644 $PKG/usr/man/man?/*

mkdir -p $PKG/install
zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
/sbin/makepkg -l y -c n $TMP/ppp-$VERSION-$ARCH-$BUILD.txz

