#!/bin/bash
########################## tools_gcc_sp1 ##########################
#
# Copyright 2021 "nobodino", Bordeaux, FRANCE
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
###################################################################
tools_gcc_sp1 () {
#*****************************
	export SRCVER=${VERSION:-$(echo gcc-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
	GCCVER=$(echo "$SRCVER" | cut -f 1 -d _)
	export GCCVER
	export MPFRVER=${VERSION:-$(echo mpfr-*.tar.?z | cut -d - -f 2 | rev | cut -f 3- -d . | rev)}
	export GMPVER=${VERSION:-$(echo gmp-*.tar.?z | cut -d - -f 2 | rev | cut -f 3- -d . | rev)}
	export LIBMPCVER=${VERSION:-$(echo mpc-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}

    tar xvf gcc-"$SRCVER".tar.?z || exit 1  
	cd gcc-"$SRCVER" || exit 1
	# apply patches to build with glibc-2.36
#	zcat ../patches/2701442d0cf6292f6624443c15813d6d1a3562fe.diff.gz | patch -Esp1 --verbose || exit 1
#	zcat ../patches/f35d65517a59565758107c5b1a51a5fa382f8d1a.diff.gz | patch -Esp1 --verbose || exit 1 

    tar xvf ../mpfr-"$MPFRVER".tar.xz
    mv -v mpfr-"$MPFRVER" mpfr
    tar xvf ../gmp-"$GMPVER".tar.?z
    mv -v gmp-"$GMPVER" gmp
    tar xvf ../mpc-"$LIBMPCVER".tar.lz
    mv -v mpc-"$LIBMPCVER" mpc

	for file in gcc/config/{linux,i386/linux{,64}}.h
	do
	  cp -uv $file{,.orig}
	  sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \
		  -e 's@/usr@/tools@g' $file.orig > $file
	  echo '
	#undef STANDARD_STARTFILE_PREFIX_1
	#undef STANDARD_STARTFILE_PREFIX_2
	#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"
	#define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
	  touch $file.orig
	done

	case $(uname -m) in
	  x86_64)
		sed -e '/m64=/s/lib64/lib/' \
		    -i.orig gcc/config/i386/t-linux64
	 ;;
	esac

	mkdir -v build 
	cd build || exit 1 

	../configure                                       \
		--target="$SFS_TGT"                            \
		--prefix=/tools                                \
		--with-glibc-version=2.11                      \
		--with-sysroot="$SFS"                          \
		--with-newlib                                  \
		--without-headers                              \
		--with-local-prefix=/tools                     \
		--with-native-system-header-dir=/tools/include \
		--disable-nls                                  \
		--disable-shared                               \
		--disable-multilib                             \
		--disable-decimal-float                        \
		--disable-threads                              \
		--disable-libatomic                            \
		--disable-libgomp                              \
		--disable-libmpx                               \
		--disable-libquadmath                          \
		--disable-libssp                               \
		--disable-libvtv                               \
		--disable-libstdcxx                            \
    	--disable-libsanitizer                         \
		--enable-languages=c,c++ || exit 1

	make || exit 1
	make install || exit 1
	cd ../..
	rm -rf gcc-"$SRCVER"
}

tools_gcc_sp1
