#!/bin/bash
########################## execute_cyrus-sasl #####################
#
# Copyright 2021 "nobodino", Bordeaux, FRANCE
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
###################################################################
execute_sed_cyrus-sasl () {
#******************************************************************
# delete several lines in SlackBuild
#******************************************************************
if [ ! -f cyrus-sasl.SlackBuild.old ]; then
	cp -v cyrus-sasl.SlackBuild cyrus-sasl.SlackBuild.old
	(
		cd "$SLACKSRC"/n/cyrus-sasl || exit 1
		sed -i -e "/--enable-sql/d" cyrus-sasl.SlackBuild
		sed -i -e "/--without-pgsql/d" cyrus-sasl.SlackBuild
		sed -i -e "/--with-mysql/d" cyrus-sasl.SlackBuild
		sed -i -e "/--with-sqlite3/d" cyrus-sasl.SlackBuild
	)
fi
}
execute_sed_cyrus-sasl
